print("Heyy , Welcome to My Profile")
print(' ')
A1=str(input("Enter your name:"))
A2=int(input("Enter your age:"))
A3=float(input("Enter your height(meter):"))
A4=int(input("Enter your favourite number:"))
print(' ')
print("Name:" , A1 , (type(A1),id(A1)))
print("Age:" , A2 , (type(A2),id(A2)))
print("Height:" , A3 , (type(A3),id(A3)))
print("Favourite Number:" , A4 , (type(A4),id(A4)))
print(' ')
Current_year = int(input("Enter current year:"))
birth_year = Current_year - A2
print(' ')
print(f"your Birth year is: {birth_year} (Based on your age of {A2})")
print(' ')
print("Thank you for visiting my profile. Have Good Day!")